name : dsde-docker
services:
  #postgres db
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
        POSTGRES_PASSWORD: strongpassword
        POSTGRES_USER: yott
        POSTGRES_DB: yottdb
    ports:
        - 5435:5432
    volumes:
        - pgdata:/var/lib/postgresql

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
        PGADMIN_DEFAULT_EMAIL: admin@example.com
        PGADMIN_DEFAULT_PASSWORD: admin
    ports:
        - 5555:80
    depends_on:
        - db

