name : dsde-docker
services:
  # --- Neo4j Graph Database ---
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - "7474:7474" # สำหรับเข้าหน้าเว็บ Browser
      - "7687:7687" # สำหรับ Python เชื่อมต่อ (Bolt)
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/import:/var/lib/neo4j/import
      - ./neo4j/plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/password123 # ตั้งรหัสผ่านที่นี่
      - NEO4J_PLUGINS=["apoc"] # แนะนำให้ลง APOC ไว้ช่วยจัดการข้อมูลกราฟ

